services:
  php:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "9000:9000"
  gdsmysql:
    image: mysql:8.0.29-oracle
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: laravel
      MYSQL_USER: pocadi
      MYSQL_PASSWORD: pocadi123
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      - PMA_HOSTS=gdsmysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
  app:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf